query posts($owner: String!, $name: String!, $last: Int!) {
  repository(owner: $owner, name: $name) {
    labels(first:20) {
      edges {
        node {
          name
        }
      }
    }
    issues(last: $last, labels: "Yong", states:OPEN) {
      totalCount
      edges {
        node {
          number
          title
          url
          id
          labels(first:2) {
            edges {
              node {
                name
                description
              }
            }
          }
        }
      }
    }
  }
}


