query post($id: ID!) {
  node (id: $id) {
    ... on Issue {
      title
      body
      bodyHTML
      labels(first:2) {
        edges {
          node {
            name
            description
          }
        }
      }
    }
  }
}


